port commodities added as constraints for placement
vmturbo/mesosturbo pull request #8
Opened 2016-08-22 18:40 UTC by pamelasanchezvi

Created port commodities based on the ports used by each container at the VMs.

2016-09-15 22:39 UTC, pamelasanchezvi commented
let me know if there is anything else to update, I have tested with 91 so far !

2016-09-16 13:38 UTC, DongyiYang commented on communicator/probe/node_probe.go
> +	/*	for _, label := range labels {
Why you comment out VMPM Access Comm

2016-09-16 14:02 UTC, DongyiYang commented on communicator/vmturbocommunicator/server_message_handler.go
>  func (handler *MesosServerMessageHandler) NewMesosProbe(previousUseMap map[string]*util.CalculatedUse) (*util.MesosAPIResponse, error) {
This is a giant method. Please extract code to new methods or functions.

2016-09-16 14:04 UTC, DongyiYang commented on communicator/vmturbocommunicator/vmt_communicator.go
> +		//		Selling(sdk.CommodityDTO_STORAGE_ALLOCATION, fakeKey).
why comment out?

2016-09-16 14:08 UTC, DongyiYang commented on communicator/vmturbocommunicator/vmt_communicator.go
> +	*/clusterType := sdk.CommodityDTO_CLUSTER
move clusterType to a new line!

2016-09-16 14:09 UTC, DongyiYang commented on communicator/vmturbocommunicator/vmt_communicator.go
> +		//		Buys(*diskAllocationTemplateComm).
We don't need diskAllocationCommodity?

2016-09-16 14:14 UTC, DongyiYang commented on mesosturbo/main.go
>  func init() {
all the vmt meta fields are set from flag? Then the command to start mesosturbo will be very very long.

2016-09-16 14:15 UTC, DongyiYang requested changes

2016-09-16 14:15 UTC, DongyiYang commented on communicator/probe/node_probe.go
> +	/*	for _, label := range labels {
why comment our VMPM access Commodity

2016-09-16 14:15 UTC, DongyiYang commented on communicator/metadata/vmt_meta.go
>  type VMTMeta struct {
I think VMTMeta is for storing the info that is used to connect to Turbo server. It shouldn't have included any field relates to Mesos, Marathon or Action

2016-09-16 14:15 UTC, DongyiYang commented on communicator/util/types.go
> +type PortUtil struct {
Add some comment about what is this **PortUtil**.

2016-09-16 14:17 UTC, pamelasanchezvi commented on communicator/probe/node_probe.go
> +	/*	for _, label := range labels {
we decided we don't support those constraints yet.

2016-09-16 14:18 UTC, pamelasanchezvi commented on communicator/metadata/vmt_meta.go
>  type VMTMeta struct {
right now it's for any connection , i'll change the name

2016-09-16 14:18 UTC, pamelasanchezvi commented on communicator/util/types.go
> +type PortUtil struct {
it's for utilization

2016-09-16 14:19 UTC, pamelasanchezvi commented on communicator/vmturbocommunicator/vmt_communicator.go
> +		//		Buys(*diskAllocationTemplateComm).
it is possible to create container without disk or disk=0

2016-09-16 18:01 UTC, DongyiYang approved these changes

2016-09-16 19:02 UTC, merged